StackOfImage.find_or_create_by(img_name: 'e1@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e2@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e3@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e4@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e5@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e6@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e7@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e8@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e9@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e10@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e11@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e12@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e13@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e14@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e15@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e16@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e17@mailcomp1.com.jpg')
StackOfImage.find_or_create_by(img_name: 'e18@mailcomp1.com.jpg')
StackOfImage.find_by(img_name: 'e1@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
StackOfImage.find_by(img_name: 'e2@mailcomp1.com.jpg').update(gender: StackOfImage::FEMALE)
StackOfImage.find_by(img_name: 'e3@mailcomp1.com.jpg').update(gender: StackOfImage::FEMALE)
StackOfImage.find_by(img_name: 'e4@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
StackOfImage.find_by(img_name: 'e5@mailcomp1.com.jpg').update(gender: StackOfImage::FEMALE)
StackOfImage.find_by(img_name: 'e6@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
StackOfImage.find_by(img_name: 'e7@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
StackOfImage.find_by(img_name: 'e8@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
StackOfImage.find_by(img_name: 'e9@mailcomp1.com.jpg').update(gender: StackOfImage::FEMALE)
StackOfImage.find_by(img_name: 'e10@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
StackOfImage.find_by(img_name: 'e11@mailcomp1.com.jpg').update(gender: StackOfImage::FEMALE)
StackOfImage.find_by(img_name: 'e12@mailcomp1.com.jpg').update(gender: StackOfImage::FEMALE)
StackOfImage.find_by(img_name: 'e13@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
StackOfImage.find_by(img_name: 'e14@mailcomp1.com.jpg').update(gender: StackOfImage::FEMALE)
StackOfImage.find_by(img_name: 'e15@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
StackOfImage.find_by(img_name: 'e16@mailcomp1.com.jpg').update(gender: StackOfImage::FEMALE)
StackOfImage.find_by(img_name: 'e17@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
StackOfImage.find_by(img_name: 'e18@mailcomp1.com.jpg').update(gender: StackOfImage::MALE)
