source 'https://rubygems.org'
ruby '2.4.1'
gem 'rails'
gem 'passenger', '4.0.57'
gem 'clockwork'
gem 'dalli'
gem 'pundit'
gem 'bcrypt'
gem 'ngmin-rails'
gem 'coffee-rails'
gem 'sass'
gem 'sass-rails', '~> 4.0.4'
gem 'compass-rails'
gem 'uglifier'
gem 'pg'
gem 'ejs'
gem 'zipruby'
gem 'yui-compressor'
gem 'aws-sdk', '1.36.0'
gem 'awesome_print'
gem 'database_cleaner'
gem 'sprockets'
gem 'descriptive-statistics'
gem 'writeexcel'
gem 'fastimage'
gem 'delayed_job_active_record'
gem 'newrelic_rpm'
gem 'oj'
gem 'oj_mimic_json'
gem 'backup'
gem 'daemons'
gem 'activerecord', '~> 4.2.0'
gem 'seed_dump'
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter', '~> 4.2.0'
gem 'mail'
gem 'font-awesome-rails'
gem 'twilio-ruby'
gem 'dotenv'
gem 'meta_request'
gem "jqcloud-rails"
gem 'literate_randomizer', '~> 0.4.0'
#gem "roo"
#gem 'roo-xls'

group :development, :test do
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'erd'
  gem 'spork'
  gem 'spork-rails'
  gem 'byebug'
  gem 'guard-spork'
  gem 'jasmine-rails'
  gem 'guard-shell'
  gem 'simplecov', require: false, group: :test
  gem 'guard-rubocop'
  gem 'colorize'
  gem 'scss-lint', '~> 0.7.0'
  gem 'transpec'
end

group :test do
  gem 'faker'
  gem 'ruby-prof'
  #gem 'selenium-webdriver', '2.35.1'
  gem 'capybara'
  gem 'libnotify'
  gem 'factory_girl_rails', '4.2.0'
end

group :production do
  gem 'rails_12factor', '0.0.2'
  gem 'heroku-deflater'
  gem 'scout_apm'
end
