source 'https://rubygems.org'
ruby '2.4.1'
gem 'rails', '5.1.0'
gem 'passenger', '4.0.57'
gem 'clockwork'
gem 'dalli'
gem 'pundit'
gem 'bcrypt'
#gem 'ngmin-rails'
gem 'coffee-rails'
gem 'sass', '3.4.1'
gem 'sass-rails'
gem 'compass-rails', '3.0.2'
gem 'uglifier'
gem 'pg'
gem 'ejs'
#gem 'zipruby'
gem "zipruby-compat", :require => 'zipruby', :git => "https://github.com/jawspeak/zipruby-compatibility-with-rubyzip-fork.git", :tag => "v0.3.7"
gem 'yui-compressor'
#gem 'aws-sdk', '1.36.0'
gem 'aws-sdk', '~> 3.0.0.rc1'
gem 'awesome_print'
gem 'database_cleaner'
gem 'sprockets'
gem 'sprockets-rails', '2.3.3'
gem 'descriptive-statistics'
gem 'writeexcel'
gem 'fastimage'
gem 'delayed_job_active_record'
gem 'newrelic_rpm'
gem 'oj'
gem 'oj_mimic_json'
gem 'backup', '3.4.0'
gem 'daemons'
gem 'activerecord', '>= 4.2.0'
gem 'seed_dump'
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter', '>= 4.2.0'
gem 'mail'
gem 'font-awesome-rails'
gem 'twilio-ruby'
gem 'dotenv'
gem 'meta_request'
gem "jqcloud-rails"
gem 'literate_randomizer', '~> 0.4.0'
#gem "roo"
gem 'roo-xls', '~>1.1.0'
gem 'hirb'

group :development, :test do
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'erd'
  gem 'spork'
#  gem 'spork-rails'
  gem 'byebug'
  gem 'guard-spork'
  gem 'jasmine-rails'
  gem 'guard-shell'
  gem 'simplecov', require: false, group: :test
  gem 'guard-rubocop'
  gem 'colorize'
  gem 'scss_lint', '~> 0.38.0'
  gem 'transpec'
end

group :test do
  gem 'faker'
  gem 'ruby-prof'
  #gem 'selenium-webdriver', '2.35.1'
  gem 'capybara'
  gem 'libnotify'
  gem 'factory_girl_rails', '4.2.0'
end

group :production do
  gem 'rails_12factor', '0.0.2'
  gem 'heroku-deflater'
  gem 'scout_apm'
end
