development:
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %>
  database: postgres
  username: postgres
  password: postgres
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000



onpremise:
  database: workships_app
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %>
  username: postgres
  password: postgres
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000


protractor:
  database: workships_protractor
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %>
  username: postgres
  password: postgres
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000


test:
  host: localhost
  port: 5432
  database: workships_test
  username: postgres
  password: postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000




# for on premise installtion
production:
  database: d3ho9e6omr0n2b
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  username: postgres
  password: postgres
  port: 5432
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
