default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] || 5432 %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  timeout: 5000

development:
  <<: *default
  #database: workships_development
  #username: workships
  #password: workships
  #port: 5432
  database: workships_app

onpremise:
  <<: *default
  database: workships_app

protractor:
  <<: *default
  database: workships_protractor

test:
  <<: *default
  datebase: localhost
  port: 5432
  username: workships
  password: workships
  database: workships_test

test-sqlserver:
  mode: dblib
  pool: 5
  adapter: sqlserver
  database: stepahead_app_db_test
  host: 192.168.1.123
  port: 1433
  username: workships
  password: workships
  timeout: 20000000

development-sqlserver:
  mode: dblib
  pool: 5
  adapter: sqlserver
  database: stepahead_app_db
  host: 192.168.1.123
  port: 1433
  username: workships
  password: workships
  timeout: 20000000

# for on premise installtion
production:
  <<: *default
  database: workships_app

production-sqlserver:
  mode: dblib
  pool: 5
  adapter: sqlserver
  database: stepahead_app_db
  host: 192.168.1.123
  port: 1433
  username: workships
  password: workships
  timeout: 20000000
